# App Name
spring.application.name=lcms

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3006/lcms
spring.datasource.username=root
spring.datasource.password=Mounish85

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8080